import { Suspense } from 'react';

import LoadingProducts from './loading';

export const metadata = {
  title: 'E-COM - Produtos',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="h-full">
      {/* Include shared UI here e.g. a header or sidebar */}
      <Suspense fallback={<LoadingProducts />}>{children}</Suspense>
    </section>
  );
}
