import './globals.css';
import { Quicksand, Poppins } from 'next/font/google';
import SessionProvider from '@/context/ContextSession';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  display: 'fallback'
});
const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt_BR">
      <body className={`${poppins.variable} ${quicksand.variable}`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
